/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bascula.gui;

import bascula.entity.Conductor;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario1
 */
public class GestorDeConductores extends javax.swing.JFrame implements bascula.gui.suscripciones.ISuscripcionBuscarConductor{
    bascula.entity.Conductor conductor;
    bascula.bussines.ConductorService service;
    bascula.gui.BuscarConductor bc;
    /**
     * Creates new form GestorDeConductores
     */
    public GestorDeConductores() {
        initComponents();
        this.jFormattedTextField1.setValue(new Long(0));
        service=new bascula.bussines.ConductorService();
    }
    public void Buscar(){
        bc=new bascula.gui.BuscarConductor();
        bc.setSuscripcion(this);
        bc.show();
        this.dispose();
    }
    public void Ingresar(){
        conductor=new bascula.entity.Conductor();
        conductor.setIdConductor((Long)this.jFormattedTextField1.getValue());
        conductor.setNombres(this.jTextField1.getText());
        conductor.setApellidos(this.jTextField2.getText());
        conductor.setReportado(this.jCheckBox1.isSelected());
        try{
        service.getController().create(conductor);
        JOptionPane.showMessageDialog(this,"Conductor Ingresado Con Exito");
        }catch(bascula.controller.exceptions.PreexistingEntityException e){
            System.out.print(e.getMessage());
            JOptionPane.showMessageDialog(this,"Ese Conductor Ya Existe");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"ERROR Hubo una Excepcion NO SE PUDO INGRESAR");
            Logger.getLogger(GestorDeConductores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Modificar(){     
        conductor.setIdConductor((Long)this.jFormattedTextField1.getValue());
        conductor.setNombres(this.jTextField1.getText());
        conductor.setApellidos(this.jTextField2.getText());
        conductor.setReportado(this.jCheckBox1.isSelected());
        try{
        service.getController().edit(conductor);
        JOptionPane.showMessageDialog(this,"Conductor Modificado Con Exito");
        this.AsignarConductor(null);
        this.jButton1.setEnabled(true);
        this.jButton3.setEnabled(false);
        this.jButton4.setEnabled(false);
        }catch(bascula.controller.exceptions.NonexistentEntityException e){
            System.out.print(e.getMessage());
            JOptionPane.showMessageDialog(this,"Ese Conductor NO Existe");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"ERROR Hubo una Excepcion NO SE PUDO Modificar");
            Logger.getLogger(GestorDeConductores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Eliminar(){     
        conductor.setIdConductor((Long)this.jFormattedTextField1.getValue());
        conductor.setNombres(this.jTextField1.getText());
        conductor.setApellidos(this.jTextField2.getText());
        conductor.setReportado(this.jCheckBox1.isSelected());
        try{
        service.getController().destroy(conductor.getIdConductor());
        JOptionPane.showMessageDialog(this,"Conductor Eliminado Con Exito");
        this.AsignarConductor(null);
        this.jButton1.setEnabled(true);
        this.jButton3.setEnabled(false);
        this.jButton4.setEnabled(false);
        }catch(bascula.controller.exceptions.NonexistentEntityException e){
            System.out.print(e.getMessage());
            JOptionPane.showMessageDialog(this,"Ese Conductor NO Existe");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"ERROR Hubo una Excepcion NO SE PUDO Eliminar");
            Logger.getLogger(GestorDeConductores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTION DE CONDUCTORES");

        jLabel2.setText("Nit/Cedula :");

        jLabel3.setText("Nombres :");

        jLabel4.setText("Apellidos :");

        jCheckBox1.setText("LISTA NEGRA");

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("Modificar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setText("Eliminar");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jMenu1.setText("Opciones");

        jMenuItem1.setText("Limpiar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jFormattedTextField1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.Ingresar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.Modificar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.Eliminar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.Buscar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.jButton1.setEnabled(true);
        this.jButton3.setEnabled(false);
        this.jButton4.setEnabled(false);
        this.AsignarConductor(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorDeConductores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void EventoDeSeleccionDeConductor() {
        this.AsignarConductor(bc.getSeleccionado());
        this.jButton1.setEnabled(false);
        this.jButton3.setEnabled(true);
        this.jButton4.setEnabled(true);
        this.show();
        bc.dispose();
    }

    @Override
    public void AsignarConductor(Conductor c) {
        this.conductor=c;
        if(c!=null){
            this.jFormattedTextField1.setValue(c.getIdConductor());
            this.jTextField1.setText(c.getNombres());
            this.jTextField2.setText(c.getApellidos());
            this.jCheckBox1.setSelected(c.getReportado());
        }else{
            this.jFormattedTextField1.setValue(new Long(0));
            this.jTextField1.setText("");
            this.jTextField2.setText("");
            this.jCheckBox1.setSelected(false);
        }
    }
}
